-- Create the users table
CREATE TABLE users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,  -- Primary key for authors
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL, 
    user_name VARCHAR(100) NOT NULL UNIQUE,      -- Name of the author
    age INT,  
    specialty VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,         -- Email address (must be unique)
);

INSERT INTO users (first_name, last_name, user_name, age, specialty, email)
VALUES
    ('John', 'Doe', 'johndoe', 25, 'Software Developer', 'johndoe@example.com'),
    ('Jane', 'Smith', 'janesmith', 30, 'Data Analyst', 'janesmith@example.com'),
    ('Michael', 'Johnson', 'mjohnson', 28, 'Network Engineer', 'mjohnson@example.com'),
    ('Emily', 'Davis', 'emilyd', 22, 'Digital Marketing Specialist', 'emilyd@example.com'),
    ('William', 'Brown', 'wbrown', 32, 'Systems Architect', 'wbrown@example.com'),
    ('Olivia', 'Wilson', 'oliviaw', 27, 'Cloud Engineer', 'oliviaw@example.com'),
    ('James', 'Martinez', 'jmartinez', 26, 'Cybersecurity Expert', 'jmartinez@example.com'),
    ('Sophia', 'Garcia', 'sophgarcia', 29, 'Machine Learning Engineer', 'sophgarcia@example.com'),
    ('Benjamin', 'Lopez', 'benlopez', 24, 'DevOps Engineer', 'benlopez@example.com'),
    ('Charlotte', 'Hernandez', 'chcharlotte', 31, 'Database Administrator', 'chcharlotte@example.com'),
    ('Liam', 'Moore', 'liammoore', 27, 'Software Tester', 'liammoore@example.com'),
    ('Mia', 'Jackson', 'miajackson', 25, 'Project Manager', 'miajackson@example.com'),
    ('Ethan', 'Taylor', 'ethantaylor', 23, 'Web Developer', 'ethantaylor@example.com'),
    ('Amelia', 'Anderson', 'ameliaa', 28, 'UX Designer', 'ameliaa@example.com'),
    ('Noah', 'Thomas', 'noaht', 33, 'Business Analyst', 'noaht@example.com'),
    ('Ava', 'Martinez', 'avam', 26, 'Full Stack Developer', 'avam@example.com'),
    ('Logan', 'Lee', 'loganl', 34, 'Solutions Architect', 'loganl@example.com'),
    ('Isabella', 'Perez', 'isaperez', 22, 'SEO Specialist', 'isaperez@example.com'),
    ('Lucas', 'Thompson', 'lucast', 29, 'Backend Developer', 'lucast@example.com'),
    ('Harper', 'White', 'harperw', 25, 'Data Scientist', 'harperw@example.com'),
    ('Henry', 'Harris', 'henryh', 27, 'Network Administrator', 'henryh@example.com'),
    ('Evelyn', 'Sanchez', 'evelyns', 31, 'Front-end Developer', 'evelyns@example.com'),
    ('Alexander', 'Clark', 'alexc', 26, 'Product Manager', 'alexc@example.com'),
    ('Ella', 'Ramirez', 'ellaram', 28, 'IT Consultant', 'ellaram@example.com'),
    ('Sebastian', 'Lewis', 'sebastianl', 24, 'Systems Analyst', 'sebastianl@example.com'),
    ('Zoe', 'Walker', 'zoew', 32, 'Technical Support Specialist', 'zoew@example.com'),
    ('Daniel', 'Robinson', 'danielr', 29, 'Software Engineer', 'danielr@example.com'),
    ('Abigail', 'Young', 'abbyy', 23, 'Data Engineer', 'abbyy@example.com'),
    ('Matthew', 'King', 'matthewk', 30, 'IT Auditor', 'matthewk@example.com'),
    ('Ella', 'Scott', 'ellascott', 25, 'Security Analyst', 'ellascott@example.com'),
    ('David', 'Green', 'davidg', 27, 'Mobile Developer', 'davidg@example.com'),
    ('Grace', 'Adams', 'gracea', 22, 'Graphics Designer', 'gracea@example.com'),
    ('Lucas', 'Baker', 'lucasb', 24, 'Database Developer', 'lucasb@example.com'),
    ('Emma', 'Nelson', 'emman', 31, 'IT Support Engineer', 'emman@example.com'),
    ('Oliver', 'Carter', 'oliverc', 26, 'Blockchain Developer', 'oliverc@example.com'),
    ('Charlotte', 'Mitchell', 'charlottem', 28, 'Cloud Administrator', 'charlottem@example.com'),
    ('Jack', 'Perez', 'jackp', 23, 'Network Specialist', 'jackp@example.com'),
    ('Avery', 'Roberts', 'averyr', 30, 'Enterprise Architect', 'averyr@example.com'),
    ('Ella', 'Collins', 'ellac', 27, 'Penetration Tester', 'ellac@example.com'),
    ('Jackson', 'Stewart', 'jacksonst', 29, 'Web Designer', 'jacksonst@example.com'),
    ('Scarlett', 'Morris', 'scarlettm', 24, 'Information Security Analyst', 'scarlettm@example.com'),
    ('Leo', 'Murphy', 'leomurphy', 32, 'Software Quality Engineer', 'leomurphy@example.com'),
    ('Victoria', 'Cook', 'viccook', 26, 'Scrum Master', 'viccook@example.com'),
    ('Elijah', 'Rogers', 'elirog', 28, 'Systems Developer', 'elirog@example.com'),
    ('Samantha', 'Reed', 'samreed', 23, 'IT Operations Specialist', 'samreed@example.com'),
    ('Lily', 'Bailey', 'lilyb', 27, 'DevOps Specialist', 'lilyb@example.com'),
    ('Gabriel', 'Rivera', 'gabrielr', 25, 'Tech Product Owner', 'gabrielr@example.com'),
    ('Hazel', 'Cooper', 'hazelc', 24, 'Solutions Engineer', 'hazelc@example.com'),
    ('David', 'Richardson', 'davidrich', 30, 'Application Developer', 'davidrich@example.com');